ml-evs/matador

docs/src/conf.py

Force sphinx to document class __init__ as well as class docstrings

---

matador/hull/hull.py
matador/plotting/battery_plotting.py
tests/test_battery.py

The previous approach to volume expansions only worked accidentally and relied on some fortuitous error cancellation between the number of formula units in the starting electrode and those in the final phases. This fixes that by explicitly working with the cell volume per fu of the starting electrode, and by balancing all reactions leading up to the final state.

Fixed ternary volume expansion approach 

---

matador/compute/__init__.py
matador/compute/compute.py
matador/workflows/castep/elastic.py
matador/workflows/castep/phonons.py
matador/workflows/castep/spectral.py
matador/workflows/workflows.py
tests/test_compute.py

This PR fixes #30 but replacing previous pure `.poll()` calls with `.communicate()`. For some reason, multi-node MPI processes always return `None` to `.poll()`, even if they have successfully returned.
This PR also refactors `ComputeTask` to be a bit cleaner and deprecates some old class names.

Patch for multi-node MPI and refactored compute

---

codecov.yml
matador/cli/dispersion.py
matador/orm/spectral/dispersion.py
matador/plotting/spectral_plotting.py
tests/test_plotting.py

Closes #39 by preventing multiple band reorderings to occur, and also disables band reordering for phonons by default.
Additional changes:
- Adds `cmap` and `band_alpha` as args to spectral plotter
- Fixes issue where empty plot would be created if files were missing
- Changed default phonon spectral plot to use slightly transparent grey bands
- Tweaked codecov settings so that they dont mark a branch as red when coverage has changed by 0.01%...

Spectral plot tweaks

---

matador/compute/batch.py
matador/fingerprints/fingerprint.py
scripts/oddjob
tests/test_compute.py
tests/test_workflows.py

Use `psutil.cpu_count(logical=False)` instead of `multiprocessing.cpu_count()` to ignore hyperthreading.

Fix misreported core count with hyperthreading

---

matador/cli/dispersion.py
matador/plotting/spectral_plotting.py
tests/test_plotting.py

e.g. `dispersion <seed> -p K:s,K:p,P:s`.

Added ability to choose which projectors are plotted with dispersion

---

matador/orm/orm.py
matador/utils/cursor_utils.py
tests/test_crystal.py

- Fixed issue where incorrect additions/deletions would be displayed when filtering for uniqueness, depending on sorting of initial cursor. This did not effect which structueres were actually filtered.
- Allow fields of `Crystal` to be set by NaN values, if they were NaN previously.

Minor fixes

---

matador/scrapers/cif_scraper.py
matador/scrapers/utils.py
scripts/pxrd_calculator
tests/data/cif_files/2.cif
tests/test_file_io.py

Closes #57.
- Handles linebreaks with a hacky, slow (but hopefully stable) char-by-char deque.
- Additionally scrapes `_space_group_symop_operation_xyz` key as alias for normal sym op key.

Fix CIF parser for awkward linebreaks

---

matador/compute/batch.py
matador/fingerprints/fingerprint.py
scripts/oddjob
tests/test_compute.py
tests/test_workflows.py

This PR closes #62 by reverting the change to `cpu_count` that took into account hyperthreading. Instead, we shall rely on error cancellation between dual-socket/non-hyperthreaded machines (the majority of x86 HPC) and revert using hyperthreading on machines where it is enabled (not ideal). Once the upstream PR is fixed in psutil, this change can be re-reverted...

Revert cpu_count change to work on dual-socket, non-hyperthreaded machines

---

matador/scrapers/castep_scrapers.py
tests/data/cell_files/kpoint_path.cell

Allows matador to read spectral paths that have the `BREAK` magic word in them. The keyword is ignored, but related functionality (e.g. dispersion script and the `ElectronicDispersion` class) will figure out the discontinuities themselves.

ENH: added support for CASTEP kpoint path `BREAK` directive

---

matador/plotting/magres_plotting.py
matador/workflows/castep/magres.py
matador/workflows/castep/spectral.py
matador/workflows/workflows.py

The main change in this PR is the addition of a DOS calculation on the high-quality SCF performed before an NMR calculation. With a bit of refactoring of the spectral workflow steps (i.e. make it so that the cell is not standardized, and the path is computed JIT) a bandstructure could be calculated too. This workflow is parameterised by the `final_elec_energy_tol` used for the magres, which defaults to `1e-11`. Relaxation steps will use the value in the param file.
This PR also has a few other side effects:

Fixes for spectral models, and added a spectral DOS step to magres workflow

---

matador/compute/batch.py
matador/fingerprints/fingerprint.py
requirements/requirements.txt
scripts/oddjob
tests/test_compute.py
tests/test_workflows.py

Thus ends the saga of #41, #62, #66... now core counting should be correct for single and multisocket machines irrespective of hyperthreading.
Closes #62.

Bump psutil to 5.7.3 to use improved core counter

---

matador/scrapers/castep_scrapers.py

As above.
CASTEP often adds new pspot library strings for each release; there is no easy way to grab them for the installed version, so we should just stop validating it.
Closes #159.

Loosen requirements when specifying pspot library

---

.github/workflows/ci.yml

The token has not been needed for a while anyway. Prompted by https://about.codecov.io/security-update/

Remove codecov token from CI

---

CHANGELOG.rst
matador/__init__.py

- Minor change: allow specification of arbitrary strings for CASTEP pseudopotential libraries (#156).
- Bug fix: standardize_cell script failing to use default symmetry tolerance value (#157).
- Bug fix: scraping of .cif files with single atoms and no symmetries (#173)
- Bug fix: scraping of Hubbard U values from .castep files, and associated bugs when performing relaxations with Hubbard U (#180)
- Dependency updates and Python 3.6 deprecation warning (#158, #181)

v0.9.11 release

---

matador/scrapers/magres_scrapers.py

CASTEP magres files store magnetic shielding information in the form:
```
ms O 99         -2.0523362330721022E+02          3.6848981558575366E+02         -2.2771013606692599E-02          3.5814867568808620E+02         -2.9946873927125921E+02         -1.0428524506521353E+00          7.9458932961222715E-03         -2.2003847124460636E-03         -5.5724953570109824E+02
```
Where O is the element and 99 is a numerical index. When that index reaches 100, the space after the O is lost, resulting in a line like:
```
ms O100         -2.0179072731970462E+02          3.6630064905427832E+02          1.2616916920493680E-02          3.5658185566204065E+02         -3.0353628246235576E+02         -1.0440187939142316E+00         -1.5038528456938940E-02          3.7592007872482180E-02 …
```

Fix failure to scrape magres files with more than 100 atoms

---

matador/plotting/magres_plotting.py
matador/utils/chem_utils.py
tests/test_chem_utils.py

Updated magres_plotting with support for empirical corrections:
cor_constant (correction constant) will apply a linear correction to the magres shift
cor_gradient (correction gradient) will apply a gradient correction to the magres shift
Updated magres_plotting to support NMR x-axis conventions:
specifying flipxaxis=true will invert the x-axis
Thank you to Angela for her contributions.

Added function to reference chemical shifts from shieldings

---

matador/scrapers/castep_scrapers.py
tests/test_file_io.py

Closes #239.
This also changes the behaviour of capturing restarts. Previously an intermediate would not be recorded if it was the first/last step in a run (i.e. the same structure that had be run twice with resampled kpoints), but now this function just records all consistent structure -> energy pairs.

Fix for reading intermediate snapshots from fixed cell calculations

---

matador/compute/compute.py
matador/scrapers/castep_scrapers.py
matador/workflows/castep/magres.py

This branch contains minor changes to allow the MagresWorkflow to work with the restart commands in a .param file for a `task : magres` restart. Importantly, at least as recently as CASTEP v22.1, this block has to be written in uppercase, so I have modified the  `compute.py` script to write this block out in `.upper()` rather than `.lower()`. 
This branch also has the following changes to the logic of the Workflow task:
- if a .check file is present in the folder, don't perform `task['scf']` 
- if `<seed>.*.mag` files are present at the start of the calculation move them to `compute_dir` because these are required to restart the `magres` calculation
- Fix typo in `magres.py` that wrote `Starting Phonon calculation` to say `Starting Magres calculation`
This is the format of the block that …

Support `continuation` and `magres_restart` in magres workflows

---

.github/workflows/ci.yml
CHANGELOG.rst
README.rst
matador/__init__.py
requirements/test_requirements.txt

- Update README with new badge format
- Pin `nbval` to avoid needing to update notebooks -- disable notebook tests for now
- Prepare v0.10.1 release

v0.10.1 release prep
