matador/battery/electrode.py, matador/config/config.py, matador/hull/hull.py, matador/hull/hull_ensemble.py, matador/hull/phase_diagram.py, matador/plotting/battery_plotting.py, matador/plotting/hull_plotting.py, matador/utils/hull_utils.py, tests/test_battery.py, tests/test_hull.py
- Enables calculation of ternary volume expansion by tracking the ratio of phases throughout ternary charge/discharge
- Rewrite and modularisation of ternary voltage calculation, which fixed bug arising from incorrect filtering of facets along the pathway
=> Overhaul ternary voltage and volume calculations

.pre-commit-config.yaml, matador/fingerprints/pdf.py, matador/plotting/pdf_plotting.py, matador/plotting/pxrd_plotting.py, requirements/pip_requirements.txt, tests/test_cell_utils.py, tests/test_plotting.py
- Added tests for PDF and PXRD plots
- Refactored other plot tests
=> Hotfix for PDF labelling

matador/plotting/plotting.py
=> Potential fix to plotting if tkinter is missing

matador/fingerprints/pxrd.py, matador/plotting/pxrd_plotting.py, scripts/pxrd_calculator
- Added several flags to `pxrd_calculator` to specify two theta range (`--two_theta_range`), rug plotting (`--rugplot`) and label control (`--spg-labels`), new default is to label with the filename.
=> Add more flags to PXRD scripts

matador/compute/compute.py, matador/export/export.py, matador/fingerprints/pxrd.py, matador/plotting/pxrd_plotting.py, scripts/pxrd_calculator
Essentially, if `write_cell_structure` wasn't specified, turn it on.
=> Change default to enable .out-cell file for higher precision positions and lattice

matador/fingerprints/pdf.py, scripts/pxrd_calculator
- Fix help strings in `pxrd_calculator`
- Change default broadening (unrolled) in PDF for ~3x speedup
=> Tweaks for fingerprints

examples/pxrd_plotting/pxrd_plotting.ipynb, examples/pymatgen_and_ase_interfaces/pymatgen_and_ase_interface.ipynb, matador/calculators/__init__.py, matador/calculators/calculator.py, matador/compute/compute.py, matador/hull/phase_diagram.py, matador/workflows/castep/__init__.py, readthedocs.yml, scripts/castep3cell, scripts/shx3cell, scripts/standardize_cell
- Removed some old stub code and fixed a few top-level imports
- Examples/docs all build correctly now with extra dependencies
- Cosmetic problems with logging in workflows were fixed
- Scripts using old `copy_pspots` parameter were updated
=> Some tidying and more minor fixes

README.rst, docs/src/examples_index.rst, docs/src/notebooks/simple_spectral.ipynb
=> Update example notebooks

matador/scrapers/castep_scrapers.py
Avoids crashes when the filename *nearly* obeys the provenance matching rules.
=> Improved error handling for filename provenance scraping

matador/plotting/convergence_plotting.py, scripts/plot_convergence
Blackened and tweaked convergence plot scripts, re-enabling the plotting of force alongside energy convergence
=> Update plot_convergence script and plots

requirements/optional_requirements.txt
See https://pymatgen.org/compatibility.html
=> Pin pymatgen version to below 2022 for now

scripts/standardize_cell
=> Fix standardize_cell CLI for symtol arg

matador/scrapers/cif_scraper.py, tests/data/cif_files/primitive.cif, tests/test_file_io.py
=> Fix scraping of single atom cif files with simple symmetries

matador/compute/compute.py, matador/scrapers/castep_scrapers.py
=> Bug fixes for multi-species Hubbard-U

.github/workflows/ci.yml, matador/__init__.py, requirements/dev_requirements.txt, requirements/docs_requirements.txt, requirements/pip_requirements.txt, requirements/requirements.txt, requirements/test_requirements.txt, requirements/viz_requirements.txt, setup.py
=> Update dependencies and add py36 deprecation warning

matador/data/atomic_scattering/atomic_scattering_factors_gsas.py, matador/data/atomic_scattering/atomic_scattering_loaders.py
=> Fix loading of GSAS scattering factors

matador/workflows/castep/magres.py, requirements/docs_requirements.txt
=> Only warn when `species_gamma` is not set at start of NMR/EFG workflow

matador/scrapers/castep_scrapers.py, tests/test_file_io.py
This PR optimizes the castep reader, significant improvements for big files (5-10x) when not needing to compute the total time or save all snapshots.
Also scrapes dispersion correction values.
=> Optimising castep file reading

matador/plotting/hull_plotting.py
- Scale and colourmap overrides
- Label only ternary phases in new style
- Fix sampmap keyword for phases above hull cutoff
=> Additional ternary hull plot tweaks

matador/plotting/battery_plotting.py, matador/utils/viz_utils.py, tests/test_viz_utils.py
- Added a method to grab a VESTA mixed colour from a chemical formula
- Added labelling and colouring parameters to plot_voltage_curve and plot_volume_curve to allow for colouring the lines by stoichiometry and adding suffices to all the labels
=> Improvements to voltage and volume plots
